FROM openjdk:17-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
ENV ALGOLIA_API_KEY=${ALGOLIA_API_KEY}
ENV DATASOURCE_URL=${DATASOURCE_URL}
ENV DATASOURCE_DRIVER=${DATASOURCE_DRIVER}
ENV DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
ENV DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
ENV DATABASE_PLATFORM=${DATABASE_PLATFORM}
ENV FE_URL=${FE_URL}

