# This is a basic workflow to help you get started with Actions

name: build docker image and publish to ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: build jar
        run: ./gradlew bootJar
      - name: create docker image
        run:  docker build --build-arg JAR_FILE=build/libs/marketplace-0.0.1-SNAPSHOT.jar -t kdg/marketplace-be .
      - name: AWS ECR
        uses: kciter/aws-ecr-action@v4
        with:
          # The AWS access key id
          access_key_id: 
          # The AWS secret access key
          secret_access_key: 
          # AWS Account ID
          account_id: 
          repo: kdg/marketplace-be
          # The AWS region
          region: 
          # Set this to true to create the repository if it does not already exist
          create_repo: true
          # Extra flags to pass to docker build (see docs.docker.com/engine/reference/commandline/build)
          extra_build_args: --build-arg JAR_FILE=build/libs/marketplace-0.0.1.jar --build-arg ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }}
          tags: latest,${{ github.sha }}
          image_scanning_configuration: true
